### PR TITLE
Remove Background portal

### PR DESCRIPTION
**Pull request by A6GibKm**
Apps shouldn't add portals manually.

### CODE REVIEW

**Comment by bermeitinger-b** [comment]
We specifically added this in #177.

Do you think the behavior has changed since then?

**Comment by bbhtt** [comment]
> Do you think the behavior has changed since then?

It seems to be working fine for me without that. In general, you don't need to add portal interfaces.

**Comment by bermeitinger-b** [comment]
It looked like Gnome specifically wanted this setting, otherwise it killed the application.

Do you use Gnome and can confirm it's not needed to run in the background?

**Comment by bbhtt** [comment]
> Do you use Gnome and can confirm it's not needed to run in the background?

Yea I'm on GNOME

[f2f0f58d54.webm](https://github.com/flathub/org.signal.Signal/assets/62639087/af3e9b1d-18ac-405a-bbfb-a0521bf14720)

**Comment by A6GibKm** [comment]
Im on GNOME too, also works.

**Comment by bermeitinger-b** [comment]
Okay then 🤷‍♀️

**Pull request merged**
