### PR TITLE
Update to v1.29.6

### PR DESCRIPTION
**Pull request by bermeitinger-b**
Signed-off-by: Bernhard Bermeitinger <bernhard.bermeitinger@gmail.com>

### CODE REVIEW

**Comment by swick** [comment]
I probably don't know enough about the flathub build infrastructure but it says build succeeded but the " Commiting builds" step failed with

    error: No gpg key found with ID 4184DD4D907A7CAE

and the testing repo is 404-ing.

**Comment by bermeitinger-b** [comment]
Yes, it seems the build servers were overloaded (?). It should be fine now.

**Comment by barthalion** [comment]
We were migrating repo server to new hardware. Things should be fine now. As you can see I also retriggered affected jobs.

**Comment by bermeitinger-b** [comment]
The build succeeded but it couldn't be published @barthalion 
`| Job failed: InternalError: Failed to run "/usr/local/lib/flat-manager/post-publish.sh" "stable" "/tank/repo/stable": No such file or directory (os error 2)`

**Pull request merged**
