### PR TITLE
Rework wayland logic by using `ELECTRON_OZONE_PLATFORM_HINT` environment variable

### PR DESCRIPTION
**Pull request by xduugu**

### CODE REVIEW

**Comment by xduugu** [comment]
Rebased against master

**Comment by pm4rcin** [comment]
@bermeitinger-b it would be great to merge this after rebase since it would allow setting global env variable for flatpak apps that people on wayland could use until chrome enables it by default.

**Comment by bermeitinger-b** [comment]
Thanks. Could you rebase again?

I guess that it should also be able to remove both x11 and wayland sockets and use x11 as fallback. We tried this a while back and electron was not working.

**Comment by pm4rcin** [comment]
If @xduugu won't rebase it for a few days I'll create a PR.

**Comment by xduugu** [comment]
Rebased again, @bermeitinger-b.

**Comment by bermeitinger-b** [comment]
bot, build

**Comment by bermeitinger-b** [comment]
Do we need to expose the variable in the yml file?

**Comment by pm4rcin** [comment]
> Do we need to expose the variable in the yml file?

I don't think so since IMO it's supposed to be global override for all Electron apps by default. If someone changes flatseal permissions he probably understands what he does.

**Comment by bermeitinger-b** [comment]
Thank you. 

Would have been a good choice to use the beta branch. But let's see what happens.

**Comment by pm4rcin** [comment]
@bermeitinger-b we forgot to try adding `fallback-x11` to make linter happy. But someone on X11 would have to test.

**Comment by bermeitinger-b** [comment]
We can try another PR for this. X11 never had any problem with any setting. It always was Wayland.

**Comment by pm4rcin** [comment]
> We can try another PR for this. X11 never had any problem with any setting. It always was Wayland.

Good to know, I didn't remember that from a few months ago. I'll create PR soon.

**Comment by bermeitinger-b** [comment]
From the past tries, when we made the linter happy, numerous issues with Wayland arose. From my understanding, the fallback to Xwayland let's it run.
I tried in a Fedora VM and could remove the X11 socket, however, this small test might not be sufficient for every case out there.

How about a PR and we'll wait for merging?

**Pull request merged**
