### PR TITLE
Add <p></p> to description text

### PR DESCRIPTION
**Pull request by jgarciao**

### CODE REVIEW

**Comment by bermeitinger-b** [comment]
bot, build

**Comment by bermeitinger-b** [comment]
@jgarciao What is the advantage of having this? I'll merge but I'm interested in the purpose.

**Comment by TingPing** [comment]
Contents of descriptions are all required to be in a <p>, <ul>, or <ol> block, this wasn't clear in the appstream spec and we are just going around fixing all apps.

**Comment by bermeitinger-b** [comment]
Thanks for clarification.

**Pull request merged**
