### PR TITLE
Use tray icon in the default .desktop file

### LINKED ISSUE #151: Feature request: Stay in tray by default
Most IM application (e.g. Pidgin, Element, Telegram Desktop) supports staying in tray icon when closed. This would be a more common default behaviour.

According the [discussion here](https://github.com/signalapp/Signal-Desktop/issues/2210#issuecomment-380383841), Signal Desktop supports `--start-in-tray` or `--use-tray-icon` as startup argument that would enable that kind of behaviour. It would be great if the flatpak package have this enabled by default.

### PR DESCRIPTION
**Pull request by yookoala**
* Add "--use-tray-icon" flag to the "Exec" of the desktop file.
* Resolve #151.

### CODE REVIEW

**Comment by yookoala** [comment]
I'm new to Flatpak. Not sure if I did it correctly.
How do I test build the Flatpak package (without flathub) and install it locally?

**Comment by yookoala** [comment]
For other developers in the future.

1. On Fedora (using dnf package manager). Open terminal and change directory into the clone of this repository:
2. Run these commands to install prerequisites (`folder-to-build-flatpak` can be whatever you want):
    ```
    sudo dnf install flatpak-builder
    flatpak install flathub org.freedesktop.Platform//19.08 org.freedesktop.Sdk//19.08 org.electronjs.Electron2.BaseApp//19.08
    flatpak-builder ./folder-to-build-flatpak org.signal.Signal.json
    cd ./folder-to-build-flatpak
    (TBC)
    ```

**Comment by yookoala** [comment]
Verified that the `--use-tray-icon` flag is added:
```
[Desktop Entry]
Name=Signal
Exec=/usr/bin/flatpak run --branch=master --arch=x86_64 --command=signal --file-forwarding org.signal.Signal --use-tray-icon @@u %U @@
Terminal=false
Type=Application
Icon=org.signal.Signal
StartupWMClass=Signal
Comment=Private messaging from your desktop
MimeType=x-scheme-handler/sgnl;
Categories=Network;InstantMessaging;Chat;
X-Flatpak-RenamedFrom=signal-desktop.desktop;
X-Flatpak=org.signal.Signal
```

P.S. Could you please add the tag #hacktoberfest to this repository. I'd like to earn a T-shirt (in the process of helping, of course).

**Comment by bermeitinger-b** [comment]
We would like to stick to the same behavior of the original program. The default desktop file from upstream does not have this parameter as default, so I prefer not to have it here as well.

**Comment by yookoala** [comment]
(sad face)

I understand.

**Pull request closed without merging**
