### PR TITLE
Update Freedesktop Runtime to 18.08

### PR DESCRIPTION
**Pull request by maximumultraist**
Exactly what it says on the tin. Hopefully this will fix some weird glitches and performance issues not seen in the uncontained app.

### CODE REVIEW

**Comment by TingPing** [comment]
Based on your comment I assume you didn't actually test this?

**Comment by bermeitinger-b** [comment]
bot, build

**Comment by bermeitinger-b** [comment]
I tried building it locally but there are no icons when selecting an attachment for a message, for example.

**Comment by maximumultraist** [comment]
I have tested this with the latest update to the 18.08 runtime and icons show up in the file selection dialog again.

**Pull request merged**
