### PR TITLE
metainfo: Use proper app id

### PR DESCRIPTION
**Pull request by A6GibKm**

### CODE REVIEW

**Comment by bermeitinger-b** [comment]
Why do you think this is necessary? What package confusion does this solve?
And shouldn't it be `org.signal.Signal-Desktop` instead? I'd rather keep it at the current state.

**Comment by A6GibKm** [comment]
The metainfo id should match the app id, which is `org.signal.Signal` (see `id` in the flatpak manifest), currently it solved this

image

some apps added the .desktop thinking it was the desktop file name, but this was incorrect and the issue propagated.

**Comment by bermeitinger-b** [comment]
Sorry, I misread the diff. The file was initially created with the old id.

Let's see if this breaks anything. (I wonder why it ever worked.)

**Comment by A6GibKm** [comment]
Some tools, have a codepath to deal with this, which is somewhat common.

**Pull request merged**
