### PR TITLE
Revert "Add --talk-name=org.freedesktop.secrets so it can talk to loc…

### PR DESCRIPTION
**Pull request by minosimo**
…al secrets storage providers"

This reverts commit a33edd142902db474dbe036b6a51190c2a5b90ac.

See https://github.com/flathub/org.signal.Signal/issues/723

### CODE REVIEW

**Comment by bermeitinger-b** [comment]
To be sure, this will break the installations where the password store was working, right?

This could be a env var similar to the whole Wayland shenanigans.

**Comment by minosimo** [comment]
I assume it would break yes. Do we have a known config where the password store works that I could test?

**Comment by bermeitinger-b** [comment]
It works for me with the environment variable `XDG_CURRENT_DESKTOP=i3:XFCE`.

I can start the beta version of Signal with `flatpak run org.signal.Signal//stable`.
The log shows 
```
[...]
2:0926/214626.912736:VERBOSE1:key_storage_util_linux.cc(51)] Password storage detected desktop environment: XFCE
[2:0926/214626.912764:VERBOSE1:key_storage_linux.cc(118)] Selected backend for OSCrypt: GNOME_LIBSECRET
[2:0926/214626.944172:VERBOSE1:key_storage_linux.cc(165)] OSCrypt using Libsecret as backend.
[...]
"level":30,"time":"2024-09-26T19:46:27.064Z","msg":"getSQLKey: decrypting key"}
```

I can just start without any other argument.

To check, I can see in Seahorse a new entry _Chromium Safe Storage_ with the application set to _Signal_. And when I set `--password-store=basic`, it tells me that it used gnome-libsecret, as expected.

**Comment by minosimo** [comment]
I attempted an MR at #738

**Comment by minosimo** [comment]
> Build [149897 successful](https://buildbot.flathub.org/#/builders/6/builds/149897) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/132989/org.signal.Signal.flatpakref
> ```

I have installed and relaunched this build several times, and it seems fine.

**Comment by bermeitinger-b** [comment]
Let's merge #738 instead.

**Pull request closed without merging**
