### PR TITLE
Update to 1.0.37

### LINKED ISSUE #1: Signal desktop is outdated
Current latest release is 1.0.37 

https://github.com/flathub/org.signal.Signal/blob/ad9e88f8e0e9e837936621d445078ade6a7a8595/org.signal.Signal.json#L40

### PR DESCRIPTION
**Pull request by Barthalion**
Fixes #1.

### CODE REVIEW

**Comment by Barthalion** [comment]
bot, build

**Comment by Barthalion** [comment]
Builds fine locally, so merging without waiting for CI.

**Comment by TingPing** [comment]
Forgot to update appdata file.

**Comment by Barthalion** [comment]
Sigh. On it.

**Pull request merged**
