### PR TITLE
Enabling camera in flatpak by setting "--device=all"

### PR DESCRIPTION
**Pull request by happychameleon**
This enables webcam support in the flatpak

### CODE REVIEW

**Comment by bermeitinger-b** [comment]
In #145, you (@happychameleon ) mention that we could set `--nodevice`. Could you add this here, so we have this functionality here, too?

**Comment by bermeitinger-b** [comment]
Thanks, does it work like intended?

**Comment by happychameleon** [comment]
I tested the build on my computer and voice and video calls worked fine

**Comment by bermeitinger-b** [comment]
Thank you very much.

**Pull request merged**
