### PR TITLE
Add access to system bus

### PR DESCRIPTION
**Pull request by taaem**
This allows Signal to access the system bus, for more information see: https://github.com/flathub/org.signal.Signal/issues/280

### CODE REVIEW

**Comment by bermeitinger-b** [comment]
Thanks, however the build server rejects this as _arbitrariy dbus access_

```
"finish-args-arbitrary-dbus-access"
```

https://buildbot.flathub.org/#/builders/5/builds/7820

**Comment by taaem** [comment]
@bermeitinger-b okay i narrowed the error more down and this happens due to electron https://github.com/electron/electron/blob/main/shell/browser/lib/power_observer_linux.cc. For reference the visual studio code flatpak fixed it in the same way https://github.com/flathub/com.visualstudio.code/issues/160

**Comment by taaem** [comment]
Just tested it and it works for me :)

**Comment by bermeitinger-b** [comment]
Could you clarify for what this bus access is needed?

**Comment by taaem** [comment]
@bermeitinger-b as far as I understand it, this is used to prevent the system from sleeping or get a signal on suspend/resume (https://github.com/electron/electron/blob/main/shell/browser/lib/power_observer_linux.cc). In Signals code I can see usage of the powerMonitor electron class ([here](https://github.com/signalapp/Signal-Desktop/blob/main/ts/main/powerChannel.ts)) which in itself uses the `power_observer_linux.cc` code (see https://github.com/electron/electron/blob/main/shell/browser/api/electron_api_power_monitor.h)

**Comment by bermeitinger-b** [comment]
Thanks! Let's test it.

**Pull request merged**
