### PR TITLE
Reintroduce Wayland

### PR DESCRIPTION
**Pull request by bermeitinger-b**
This PR reintroduces Wayland and tracks its progress.

We should wait until a few different users confirm that it works on Wayland.

### CODE REVIEW

**Comment by Altonss** [comment]
> `flatpak install --user https://dl.flathub.org/build-repo/85559/org.signal.Signal.flatpakref`

It is weird but this command alone doesn't work, is this normal?

**Comment by Altonss** [comment]
> It is weird but this command alone doesn't work, is this normal?

It finally worked with the latest build (it was a problem on my vm, sorry ^^) but the fullscreen issue is remaining...so not "mergeable" for the moment

**Review by Altonss — CHANGES_REQUESTED** [review]
The fullscreen issue is remaining, so for now this code cannot get merged until it is fixed

**Comment by meeuw** [comment]
I'd love to test this but I get the following error message:
```
$ flatpak install --user https://dl.flathub.org/build-repo/86085/org.signal.Signal.flatpakref
error: Can't load uri https://dl.flathub.org/build-repo/86085/org.signal.Signal.flatpakref: Server returned status 404: Not Found
```

**Comment by bermeitinger-b** [comment]
Bot, build

**Comment by meeuw** [comment]
Works like a charm!

I'd really like to get this merged, this fixes the crashes on resize for me on Wayland (Fedora).

All "close buttons" work for me, preference window is indeed opened at a weird location.

**Comment by Altonss** [comment]
The issue is still there :/

**Comment by meeuw** [comment]
> The issue is still there :/

What's the problem with fullscreen?

**Comment by Altonss** [comment]
> > The issue is still there :/
> 
> What's the problem with fullscreen?

Yes the problem with fullscreen!

**Comment by joshua-stone** [comment]
@bermeitinger-b Would it make sense to slowly introduce Wayland support as an optional feature for now? In the case of Obsidian an environment variable is set so it can be enabled for testing support:

https://github.com/flathub/md.obsidian.Obsidian#wayland-support
https://github.com/flathub/md.obsidian.Obsidian/blob/master/obsidian.sh#L13

Support could be introduced in the following steps:

1) Deploy Signal with `SIGNAL_USE_WAYLAND=0` set as well as documenting how to enable it for testing
2) Once Wayland support is mature enough, deploy Signal with `SIGNAL_USE_WAYLAND=1` and document a fallback to XWayland.
4) Eventually, once support has reached a level of maturity where most Wayland-specific bugs are fixed (and ideally enabled in upstream Signal), remove `OBSIDIAN_USE_WAYLAND` and have Signal enable Wayland when available.

Does that sound good?

**Comment by bermeitinger-b** [comment]
Sure, if it's mature enough, I won't stand in the way of your PR.


I don't have the time and environment to develop and test.

**Comment by bermeitinger-b** [comment]
Superseded by #342

**Pull request closed without merging**
