### PR TITLE
Trigger rebuild

### PR DESCRIPTION
**Pull request by bermeitinger-b**

### CODE REVIEW

**Comment by A6GibKm** [comment]
Did you try this patch both in  x11 and a wayland session?

**Comment by bermeitinger-b** [comment]
I didn't have any problem to begin with, so no.

**Comment by A6GibKm** [comment]
Just to be clear, this makes it so that the app can exclusively use either of x11 or wayland. If the app and toolkit behave well, this is desired if not can cause issues, e.g. qt 5 apps.

**Comment by bermeitinger-b** [comment]
Okay, then, let's not merge for the moment. There was a reason, both sockets were listed.

The linter complains having both, so the sensible choice would be having this at some point in the future.

**Comment by bbhtt** [comment]
It immediately closes on GNOME wayland if `--env=SIGNAL_USE_WAYLAND=1` is not passed (Which is the default)

**Comment by bermeitinger-b** [comment]
Yes, that is known that it needs this horrible wayland workaround. However, we could drop this env var and try again?

**Comment by A6GibKm** [comment]
> Okay, then, let's not merge for the moment. There was a reason, both sockets were listed.
> 
> The linter complains having both, so the sensible choice would be having this at some point in the future.

That linter issue is just a warning, the real reason is a bug that crashes in the linter. 

By the way, in the past electron didn't work without x11 access, with time they have improved their wayland story, but it might be yet a bit to early to enable it completely.

**Comment by bermeitinger-b** [comment]
Yeah, the warning caused the linter to crash. So we have für https://github.com/flathub/flatpak-builder-lint/pull/184 to be merged until we can rebuild again.

**Comment by hfiguiere** [comment]
bot, build

**Comment by bermeitinger-b** [comment]
It build correctly. Let's not merge this until wayland is perfectly supported by Electron and Flatpak and in general.

**Comment by hfiguiere** [comment]
then it should be `fallback-x11` for wayland support.

**Comment by hfiguiere** [comment]
then that's not "wayland is perfectly supported"

**Comment by bermeitinger-b** [comment]
Exactly, that's why it's not merged.

**Pull request closed without merging**
