### PR TITLE
Update to 1.0.39

### PR DESCRIPTION
**Pull request by bermeitinger-b**

### CODE REVIEW

**Comment by Barthalion** [comment]
bot, build

**Comment by Barthalion** [comment]
LGTM. Would you like to become co-maintainer? You're already doing better job at maintaining this one than me.

**Comment by bermeitinger-b** [comment]
Hi, sorry for answering so late. I don't have enough knowledge about flathub or flatpak that I would consider myself a maintainer. I would be lost if there were a bigger change than changing a few lines to the new version.

**Comment by Barthalion** [comment]
I wouldn't worry too much about it, there is a CI for testing changes and I'm usually more involved with helping contributors than tracking new releases… Give it some thought, but obviously it's completely up to you.

**Comment by TingPing** [comment]
Yea just bumping versions and running it is 90% of the work, for anything beyond that you can just open an issue.

**Pull request merged**
