### PR TITLE
Trying to fix #92

### LINKED ISSUE #92: Signal 1.27.1 will not run
When trying to start Signal 1.27.1, it fails to load with the following error:

`
$ flatpak run org.signal.Signal

[2:0906/090612.388077:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/Signal/chrome-sandbox is owned by root and has mode 4755.
`

This is on an up-to-date Fedora 30 system on an x86_64 desktop computer.

### PR DESCRIPTION
**Pull request by bermeitinger-b**

### CODE REVIEW

**Comment by bermeitinger-b** [comment]
This disables the electron sandbox by adding the parameter `--no-sandbox` to the app start. I didn't find another possibility @barthalion

**Comment by Cerberus0** [comment]
Consider updating the app to version 1.27.2 first. The changelog [says](https://github.com/signalapp/Signal-Desktop/releases/tag/v1.27.2):

>Fixes a startup issue present on some Linux distributions.

It may or may not fix https://github.com/flathub/org.signal.Signal/issues/92.

**Comment by SISheogorath** [comment]
LOL:

https://github.com/signalapp/Signal-Desktop/commit/1ca0d821078286d5953cf0d598e6b97710f816ef

It simply forces --no-sandbox into the desktop file. That's definitely not how it's supposed to work…

**Comment by bermeitinger-b** [comment]
Apparently, they do the same thing in 1.27.2 as this pull requests suggest. So, I'm closing this in favour of the update.

**Comment by SISheogorath** [comment]
When I saw it correct, this PR would still be required since flatpak doesn't use the same desktop file.

**Comment by binnih** [comment]
Same problem with 1.27.2

**Pull request closed without merging**
