### PR TITLE
V1.21.1

### PR DESCRIPTION
**Pull request by bermeitinger-b**

### CODE REVIEW

**Comment by bermeitinger-b** [comment]
bot, build

**Comment by xduugu** [comment]
How about removing the application icon that breaks the build? It's not a real fix, but at least the app can be built again.

```
diff --git a/org.signal.Signal.json b/org.signal.Signal.json
index cb64ed9..e441607 100644
--- a/org.signal.Signal.json
+++ b/org.signal.Signal.json
@@ -28,6 +28,7 @@
                 "tar xf data.tar.xz",
                 "rm -f control.tar.gz data.tar.xz debian-binary",
                 "cp -r usr/* opt/* /app",
+                "rm -rf /app/share/icons/hicolor/1024x1024/",
                 "chmod -R a-s,go+rX,go-w /app/Signal",
                 "sed -i 's|Exec=.*|Exec=signal %U|' /app/share/applications/signal-desktop.desktop",
                 "install signal.sh /app/bin/signal",
```

**Comment by bermeitinger-b** [comment]
bot, build

**Comment by bermeitinger-b** [comment]
bot, build

**Pull request merged**
